examples, test: Switch to using spec.description
Our policies were written under an incorrect format, where we were
setting a top-level description instead of using the already existing
spec.description field. Since upgrading our CRDs to v1, this causes
validation errors when applying these YAMLs:

```
$ kubectl apply -f test/k8sT/manifests/cnp-update-allow-all.yaml
error: error validating "test/k8sT/manifests/cnp-update-allow-all.yaml":
error validating data: ValidationError(CiliumNetworkPolicy): unknown
field "description" in io.cilium.v2.CiliumNetworkPolicy; if you choose
to ignore these errors, turn validation off with --validate=false
```

This commit migrates our use of the incorrect field to the correct
location. Note that policies can still be created with a top-level
description field due to support from our fork of controller-tools, see
commit:
https://github.com/christarazi/controller-tools/commit/e0828e0bacb236d2122d42b94c0788b3a0efc064

Support for the top-level description field will likely be removed in
future versions of Cilium.

Related: https://github.com/cilium/cilium/issues/13155

Signed-off-by: Chris Tarazi <chris@isovalent.com>